name: Build

on:
  push:
    branches: ["main"]
    paths-ignore:
      - '**/.*'   # all dot‑files & dot‑folders
      - '**/*.md'

  pull_request:
    paths-ignore:
      - '**/.*'   # all dot‑files & dot‑folders
      - '**/*.md'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build